# Generated by Django 4.2.8 on 2023-12-15 09:43

import cooking_manager.user_app.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_create_base_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='user_app.person')),
            ],
            options={
                'abstract': False,
            },
            bases=('user_app.baseuser',),
            managers=[
                ('objects', cooking_manager.user_app.manager.UserAppManager()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(blank=True, related_name='family_members', to='user_app.person')),
            ],
        ),
    ]
