# Generated by Django 5.0 on 2023-12-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('parent_category',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                   to='recipe.recipecategory')),
            ],
        ),
    ]
